USE SCHEMA MTD;
CREATE OR REPLACE TABLE MTD.MTD_SRC_TABLE (	SRC_TABLE_ID	INTEGER	,
	SRC_TABLE_DATABASE	STRING	,
	SRC_TABLE_SCHEMA	STRING	,
	SRC_TABLE_NAME	STRING	,
	SRC_VALUE_COLUMN	STRING	,
	SRC_TABLE_DESC	STRING	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_SRC_COLUMN (	SRC_COLUMN_ID	INTEGER	,
	SRC_TABLE_ID	INTEGER	,
	ARRAY_PATH STRING,
	SRC_COLUMN	STRING	,
	SRC_COLUMN_DATA_TYPE	STRING	,
	FILTER_CRITERIA	STRING	,
	SRC_COLUMN_DESC	STRING	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_SAT (	SAT_TABLE_ID	INTEGER	,
	SAT_TABLE_NAME	STRING	,
	SRC_TABLE_ID	INTEGER	,
	HUB_TABLE_ID	INTEGER	,
	LINK_TABLE_ID	INTEGER	,
	MULTI_ACTIV_SAT	BOOLEAN DEFAULT FALSE	,
	HASH_DIFF	BOOLEAN DEFAULT FALSE	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_SAT_MAP (	SRC_TABLE_ID	INTEGER	,
	SRC_COLUMN_ID	INTEGER	,
	SAT_TABLE_ID	INTEGER	,
	SAT_COLUMN	STRING	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_HUB (	HUB_TABLE_ID	INTEGER	,
	HUB_TABLE_NAME	STRING	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_HUB_MAP (	SRC_TABLE_ID	INTEGER	,
	SRC_COLUMN_ID	INTEGER	,
	HUB_TABLE_ID	INTEGER	,
	HUB_COLUMN	STRING	,
	HUB_COLUMN_ORDER_ID	INTEGER	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_LINK (	LINK_TABLE_ID	INTEGER	,
	LINK_TABLE_NAME	STRING	,
	NON_HIST_LINK	BOOLEAN DEFAULT FALSE	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_LINK_HUB_REF (	LINK_TABLE_ID	INTEGER	,
	SRC_TABLE_ID	INTEGER	,
	HUB_TABLE_ID	INTEGER	,
	HUB_ORDER_ID	INTEGER	,
	VERSION_ID	INTEGER	);
			
CREATE OR REPLACE TABLE MTD.MTD_METADATA_LOG (	VERSION_ID	INTEGER	,
	LOAD_DTS	TIMESTAMP	);
			
CREATE OR REPLACE TABLE MTD.MTD_TEMPLATE_VERSION (	TEMPLATE_VERSION_ID	INTEGER	,
	LOAD_DTS	TIMESTAMP	);
			
CREATE OR REPLACE TABLE MTD.MTD_MODEL_CREATION_LOG (	TEMPLATE_VERSION_ID	INTEGER	,
	VERSION_ID	INTEGER	,
	APPROVAL	BOOLEAN DEFAULT FALSE	,
	CREATION_DTS	TIMESTAMP	);
			
CREATE OR REPLACE TABLE MTD.MTD_LINK_MAP (	SRC_TABLE_ID	INTEGER	,
	SRC_COLUMN_ID	INTEGER	,
	LINK_TABLE_ID	INTEGER	,
	LINK_COLUMN	STRING	,
	VERSION_ID	INTEGER	);

CREATE OR REPLACE TABLE MTD.ETL_SQL (TYPE STRING,
	VERSION_ID INTEGER,
	SRC_TABLE_NAME STRING,
	TGT_TABLE_NAME STRING,
	INIT_FG BOOLEAN, 
	ETL_SQL STRING);